package com.vkui.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.runtime.Immutable

@Immutable
class VkColorScheme(
    val colorBackgroundAccent: Color,
    val colorBackgroundAccentThemed: Color,
    val colorBackgroundAccentThemedAlpha: Color,
    val colorBackgroundAccentTint: Color,
    val colorBackgroundAccentAlternative: Color,
    val colorBackground: Color,
    val colorBackgroundContent: Color,
    val colorBackgroundContentAlpha: Color,
    val colorBackgroundContentInverse: Color,
    val colorBackgroundSecondary: Color,
    val colorBackgroundSecondaryAlpha: Color,
    val colorBackgroundTertiary: Color,
    val colorBackgroundTertiaryAlpha: Color,
    val colorBackgroundContrast: Color,
    val colorBackgroundContrastSecondaryAlpha: Color,
    val colorBackgroundContrastInverse: Color,
    val colorBackgroundContrastThemed: Color,
    val colorBackgroundModal: Color,
    val colorBackgroundModalInverse: Color,
    val colorBackgroundPositive: Color,
    val colorBackgroundPositiveTint: Color,
    val colorBackgroundWarning: Color,
    val colorBackgroundNegative: Color,
    val colorBackgroundNegativeTint: Color,
    val colorBackgroundInfoTint: Color,
    val colorFieldBackground: Color,
    val colorHeaderBackground: Color,
    val colorTextAccent: Color,
    val colorTextAccentThemed: Color,
    val colorTextPrimary: Color,
    val colorTextPrimaryAlpha: Color,
    val colorTextPrimaryInvariably: Color,
    val colorTextSecondary: Color,
    val colorTextSecondaryAlpha: Color,
    val colorTextSubhead: Color,
    val colorTextTertiary: Color,
    val colorTextContrast: Color,
    val colorTextContrastThemed: Color,
    val colorTextPositive: Color,
    val colorTextNegative: Color,
    val colorTextLink: Color,
    val colorTextLinkThemed: Color,
    val colorTextLinkTint: Color,
    val colorTextLinkVisited: Color,
    val colorTextMuted: Color,
    val colorLinkContrast: Color,
    val colorIconAccent: Color,
    val colorIconAccentThemed: Color,
    val colorIconPrimary: Color,
    val colorIconPrimaryInvariably: Color,
    val colorIconMedium: Color,
    val colorIconMediumAlpha: Color,
    val colorIconSecondary: Color,
    val colorIconSecondaryAlpha: Color,
    val colorIconTertiary: Color,
    val colorIconTertiaryAlpha: Color,
    val colorIconContrast: Color,
    val colorIconContrastThemed: Color,
    val colorIconContrastSecondary: Color,
    val colorIconPositive: Color,
    val colorIconWarning: Color,
    val colorIconNegative: Color,
    val colorStrokeAccent: Color,
    val colorStrokeAccentThemed: Color,
    val colorSeparatorPrimary: Color,
    val colorSeparatorPrimary2x: Color,
    val colorSeparatorPrimary3x: Color,
    val colorSeparatorPrimaryAlpha: Color,
    val colorSeparatorSecondary: Color,
    val colorStrokePositive: Color,
    val colorStrokeNegative: Color,
    val colorStrokeContrast: Color,
    val colorStrokePrimary: Color,
    val colorImageBorderAlpha: Color,
    val colorFieldBorderAlpha: Color,
    val colorAccentBlue: Color,
    val colorAccentGray: Color,
    val colorAccentRed: Color,
    val colorAccentOrangeFire: Color,
    val colorAccentOrange: Color,
    val colorAccentOrangePeach: Color,
    val colorAccentLime: Color,
    val colorAccentGreen: Color,
    val colorAccentCyan: Color,
    val colorAccentAzure: Color,
    val colorAccentPurple: Color,
    val colorAccentViolet: Color,
    val colorAccentRaspberryPink: Color,
    val colorAccentPink: Color,
    val colorAccentSecondary: Color,
    val colorOverlayPrimary: Color,
    val colorOverlaySecondary: Color,
    val colorAvatarOverlay: Color,
    val colorAvatarOverlayInverseAlpha: Color,
    val colorActionSheetText: Color,
    val colorImagePlaceholder: Color,
    val colorImagePlaceholderAlpha: Color,
    val colorSkeletonFrom: Color,
    val colorSkeletonTo: Color,
    val colorButtonText: Color,
    val colorButtonIcon: Color,
    val colorButtonStroke: Color,
    val colorWriteBarIcon: Color,
    val colorWriteBarInputBackground: Color,
    val colorWriteBarInputBorder: Color,
    val colorWriteBarInputBorderAlpha: Color,
    val colorTrackBackground: Color,
    val colorTrackBuffer: Color,
    val colorSearchFieldBackground: Color,
    val colorPanelHeaderIcon: Color,
    val colorSegmentedControl: Color,
    val colorTabbarTextInactive: Color,
    val colorTransparent: Color,
)

fun vkontakteAndroidColorScheme(
    colorBackgroundAccent: Color = Color(0xFF2688EB),
    colorBackgroundAccentThemed: Color = Color(0xFF2688EB),
    colorBackgroundAccentThemedAlpha: Color = Color(0x332688EB),
    colorBackgroundAccentTint: Color = Color(0xFF5A9EFF),
    colorBackgroundAccentAlternative: Color = Color(0xFF2688EB),
    colorBackground: Color = Color(0xFFEBEDF0),
    colorBackgroundContent: Color = Color(0xFFFFFFFF),
    colorBackgroundContentAlpha: Color = Color(0xCCFFFFFF),
    colorBackgroundContentInverse: Color = Color(0xFF19191A),
    colorBackgroundSecondary: Color = Color(0xFFF5F5F5),
    colorBackgroundSecondaryAlpha: Color = Color(0x0A000000),
    colorBackgroundTertiary: Color = Color(0xFFF9F9F9),
    colorBackgroundTertiaryAlpha: Color = Color(0x07000000),
    colorBackgroundContrast: Color = Color(0xFFFFFFFF),
    colorBackgroundContrastSecondaryAlpha: Color = Color(0x33FFFFFF),
    colorBackgroundContrastInverse: Color = Color(0xFF2C2D2E),
    colorBackgroundContrastThemed: Color = Color(0xFFFFFFFF),
    colorBackgroundModal: Color = Color(0xFFFFFFFF),
    colorBackgroundModalInverse: Color = Color(0xFF1C1D1E),
    colorBackgroundPositive: Color = Color(0xFF4BB34B),
    colorBackgroundPositiveTint: Color = Color(0xFFE8F9E8),
    colorBackgroundWarning: Color = Color(0xFFFFF2D6),
    colorBackgroundNegative: Color = Color(0xFFE64646),
    colorBackgroundNegativeTint: Color = Color(0xFFFFE9E9),
    colorBackgroundInfoTint: Color = Color(0xFFDEEEFF),
    colorFieldBackground: Color = Color(0xFFF2F3F5),
    colorHeaderBackground: Color = Color(0xFFFFFFFF),
    colorTextAccent: Color = Color(0xFF2688EB),
    colorTextAccentThemed: Color = Color(0xFF2688EB),
    colorTextPrimary: Color = Color(0xFF000000),
    colorTextPrimaryAlpha: Color = Color(0xD625292E),
    colorTextPrimaryInvariably: Color = Color(0xFF000000),
    colorTextSecondary: Color = Color(0xFF818C99),
    colorTextSecondaryAlpha: Color = Color(0x8C25292E),
    colorTextSubhead: Color = Color(0xFF6D7885),
    colorTextTertiary: Color = Color(0xFF99A2AD),
    colorTextContrast: Color = Color(0xFFFFFFFF),
    colorTextContrastThemed: Color = Color(0xFFFFFFFF),
    colorTextPositive: Color = Color(0xFF4BB34B),
    colorTextNegative: Color = Color(0xFFE64646),
    colorTextLink: Color = Color(0xFF2D81E0),
    colorTextLinkThemed: Color = Color(0xFF2D81E0),
    colorTextLinkTint: Color = Color(0xFF71AAEB),
    colorTextLinkVisited: Color = Color(0xFF4986CC),
    colorTextMuted: Color = Color(0xFF2C2D2E),
    colorLinkContrast: Color = Color(0xFFFFFFFF),
    colorIconAccent: Color = Color(0xFF2688EB),
    colorIconAccentThemed: Color = Color(0xFF2688EB),
    colorIconPrimary: Color = Color(0xFF2C2D2E),
    colorIconPrimaryInvariably: Color = Color(0xFF2C2D2E),
    colorIconMedium: Color = Color(0xFF818C99),
    colorIconMediumAlpha: Color = Color(0x7A000000),
    colorIconSecondary: Color = Color(0xFF99A2AD),
    colorIconSecondaryAlpha: Color = Color(0x5B000000),
    colorIconTertiary: Color = Color(0xFFB8C1CC),
    colorIconTertiaryAlpha: Color = Color(0x3D000000),
    colorIconContrast: Color = Color(0xFFFFFFFF),
    colorIconContrastThemed: Color = Color(0xFFFFFFFF),
    colorIconContrastSecondary: Color = Color(0xFFF2F3F5),
    colorIconPositive: Color = Color(0xFF4BB34B),
    colorIconWarning: Color = Color(0xFFF8A01C),
    colorIconNegative: Color = Color(0xFFE64646),
    colorStrokeAccent: Color = Color(0xFF2688EB),
    colorStrokeAccentThemed: Color = Color(0xFF2688EB),
    colorSeparatorPrimary: Color = Color(0xFFD7D8D9),
    colorSeparatorPrimary2x: Color = Color(0xFFCBCCCD),
    colorSeparatorPrimary3x: Color = Color(0xFFBEBFC1),
    colorSeparatorPrimaryAlpha: Color = Color(0x1E000000),
    colorSeparatorSecondary: Color = Color(0xFFE1E3E6),
    colorStrokePositive: Color = Color(0xFF4BB34B),
    colorStrokeNegative: Color = Color(0xFFE64646),
    colorStrokeContrast: Color = Color(0xFFFFFFFF),
    colorStrokePrimary: Color = Color(0xFF2C2D2E),
    colorImageBorderAlpha: Color = Color(0x14000000),
    colorFieldBorderAlpha: Color = Color(0x1E000000),
    colorAccentBlue: Color = Color(0xFF2688EB),
    colorAccentGray: Color = Color(0xFFA3ADB8),
    colorAccentRed: Color = Color(0xFFFF3347),
    colorAccentOrangeFire: Color = Color(0xFFF05C44),
    colorAccentOrange: Color = Color(0xFFFFA000),
    colorAccentOrangePeach: Color = Color(0xFFF9B54F),
    colorAccentLime: Color = Color(0xFFAFF70D),
    colorAccentGreen: Color = Color(0xFF4BB34B),
    colorAccentCyan: Color = Color(0xFF13FFD0),
    colorAccentAzure: Color = Color(0xFF0077FF),
    colorAccentPurple: Color = Color(0xFF735CE6),
    colorAccentViolet: Color = Color(0xFF792EC0),
    colorAccentRaspberryPink: Color = Color(0xFFE03FAB),
    colorAccentPink: Color = Color(0xFFF45FFF),
    colorAccentSecondary: Color = Color(0xFF3F8AE0),
    colorOverlayPrimary: Color = Color(0x66000000),
    colorOverlaySecondary: Color = Color(0x44000000),
    colorAvatarOverlay: Color = Color(0x99000000),
    colorAvatarOverlayInverseAlpha: Color = Color(0xD8FFFFFF),
    colorActionSheetText: Color = Color(0xFF3F8AE0),
    colorImagePlaceholder: Color = Color(0xFFF2F3F5),
    colorImagePlaceholderAlpha: Color = Color(0x14001C3D),
    colorSkeletonFrom: Color = Color(0xFFF5F5F5),
    colorSkeletonTo: Color = Color(0xFFE1E3E6),
    colorButtonText: Color = Color(0xFF2688EB),
    colorButtonIcon: Color = Color(0xFF2688EB),
    colorButtonStroke: Color = Color(0xFF2688EB),
    colorWriteBarIcon: Color = Color(0xFF3F8AE0),
    colorWriteBarInputBackground: Color = Color(0xFFF2F3F5),
    colorWriteBarInputBorder: Color = Color(0xFFE1E3E6),
    colorWriteBarInputBorderAlpha: Color = Color(0x14000000),
    colorTrackBackground: Color = Color(0xFFE1E3E6),
    colorTrackBuffer: Color = Color(0xFFA0BFE4),
    colorSearchFieldBackground: Color = Color(0xFFEBEDF0),
    colorPanelHeaderIcon: Color = Color(0xFF2688EB),
    colorSegmentedControl: Color = Color(0xFFFFFFFF),
    colorTabbarTextInactive: Color = Color(0xFF99A2AD),
    colorTransparent: Color = Color(0x00000000),
) = VkColorScheme(
    colorBackgroundAccent = colorBackgroundAccent,
    colorBackgroundAccentThemed = colorBackgroundAccentThemed,
    colorBackgroundAccentThemedAlpha = colorBackgroundAccentThemedAlpha,
    colorBackgroundAccentTint = colorBackgroundAccentTint,
    colorBackgroundAccentAlternative = colorBackgroundAccentAlternative,
    colorBackground = colorBackground,
    colorBackgroundContent = colorBackgroundContent,
    colorBackgroundContentAlpha = colorBackgroundContentAlpha,
    colorBackgroundContentInverse = colorBackgroundContentInverse,
    colorBackgroundSecondary = colorBackgroundSecondary,
    colorBackgroundSecondaryAlpha = colorBackgroundSecondaryAlpha,
    colorBackgroundTertiary = colorBackgroundTertiary,
    colorBackgroundTertiaryAlpha = colorBackgroundTertiaryAlpha,
    colorBackgroundContrast = colorBackgroundContrast,
    colorBackgroundContrastSecondaryAlpha = colorBackgroundContrastSecondaryAlpha,
    colorBackgroundContrastInverse = colorBackgroundContrastInverse,
    colorBackgroundContrastThemed = colorBackgroundContrastThemed,
    colorBackgroundModal = colorBackgroundModal,
    colorBackgroundModalInverse = colorBackgroundModalInverse,
    colorBackgroundPositive = colorBackgroundPositive,
    colorBackgroundPositiveTint = colorBackgroundPositiveTint,
    colorBackgroundWarning = colorBackgroundWarning,
    colorBackgroundNegative = colorBackgroundNegative,
    colorBackgroundNegativeTint = colorBackgroundNegativeTint,
    colorBackgroundInfoTint = colorBackgroundInfoTint,
    colorFieldBackground = colorFieldBackground,
    colorHeaderBackground = colorHeaderBackground,
    colorTextAccent = colorTextAccent,
    colorTextAccentThemed = colorTextAccentThemed,
    colorTextPrimary = colorTextPrimary,
    colorTextPrimaryAlpha = colorTextPrimaryAlpha,
    colorTextPrimaryInvariably = colorTextPrimaryInvariably,
    colorTextSecondary = colorTextSecondary,
    colorTextSecondaryAlpha = colorTextSecondaryAlpha,
    colorTextSubhead = colorTextSubhead,
    colorTextTertiary = colorTextTertiary,
    colorTextContrast = colorTextContrast,
    colorTextContrastThemed = colorTextContrastThemed,
    colorTextPositive = colorTextPositive,
    colorTextNegative = colorTextNegative,
    colorTextLink = colorTextLink,
    colorTextLinkThemed = colorTextLinkThemed,
    colorTextLinkTint = colorTextLinkTint,
    colorTextLinkVisited = colorTextLinkVisited,
    colorTextMuted = colorTextMuted,
    colorLinkContrast = colorLinkContrast,
    colorIconAccent = colorIconAccent,
    colorIconAccentThemed = colorIconAccentThemed,
    colorIconPrimary = colorIconPrimary,
    colorIconPrimaryInvariably = colorIconPrimaryInvariably,
    colorIconMedium = colorIconMedium,
    colorIconMediumAlpha = colorIconMediumAlpha,
    colorIconSecondary = colorIconSecondary,
    colorIconSecondaryAlpha = colorIconSecondaryAlpha,
    colorIconTertiary = colorIconTertiary,
    colorIconTertiaryAlpha = colorIconTertiaryAlpha,
    colorIconContrast = colorIconContrast,
    colorIconContrastThemed = colorIconContrastThemed,
    colorIconContrastSecondary = colorIconContrastSecondary,
    colorIconPositive = colorIconPositive,
    colorIconWarning = colorIconWarning,
    colorIconNegative = colorIconNegative,
    colorStrokeAccent = colorStrokeAccent,
    colorStrokeAccentThemed = colorStrokeAccentThemed,
    colorSeparatorPrimary = colorSeparatorPrimary,
    colorSeparatorPrimary2x = colorSeparatorPrimary2x,
    colorSeparatorPrimary3x = colorSeparatorPrimary3x,
    colorSeparatorPrimaryAlpha = colorSeparatorPrimaryAlpha,
    colorSeparatorSecondary = colorSeparatorSecondary,
    colorStrokePositive = colorStrokePositive,
    colorStrokeNegative = colorStrokeNegative,
    colorStrokeContrast = colorStrokeContrast,
    colorStrokePrimary = colorStrokePrimary,
    colorImageBorderAlpha = colorImageBorderAlpha,
    colorFieldBorderAlpha = colorFieldBorderAlpha,
    colorAccentBlue = colorAccentBlue,
    colorAccentGray = colorAccentGray,
    colorAccentRed = colorAccentRed,
    colorAccentOrangeFire = colorAccentOrangeFire,
    colorAccentOrange = colorAccentOrange,
    colorAccentOrangePeach = colorAccentOrangePeach,
    colorAccentLime = colorAccentLime,
    colorAccentGreen = colorAccentGreen,
    colorAccentCyan = colorAccentCyan,
    colorAccentAzure = colorAccentAzure,
    colorAccentPurple = colorAccentPurple,
    colorAccentViolet = colorAccentViolet,
    colorAccentRaspberryPink = colorAccentRaspberryPink,
    colorAccentPink = colorAccentPink,
    colorAccentSecondary = colorAccentSecondary,
    colorOverlayPrimary = colorOverlayPrimary,
    colorOverlaySecondary = colorOverlaySecondary,
    colorAvatarOverlay = colorAvatarOverlay,
    colorAvatarOverlayInverseAlpha = colorAvatarOverlayInverseAlpha,
    colorActionSheetText = colorActionSheetText,
    colorImagePlaceholder = colorImagePlaceholder,
    colorImagePlaceholderAlpha = colorImagePlaceholderAlpha,
    colorSkeletonFrom = colorSkeletonFrom,
    colorSkeletonTo = colorSkeletonTo,
    colorButtonText = colorButtonText,
    colorButtonIcon = colorButtonIcon,
    colorButtonStroke = colorButtonStroke,
    colorWriteBarIcon = colorWriteBarIcon,
    colorWriteBarInputBackground = colorWriteBarInputBackground,
    colorWriteBarInputBorder = colorWriteBarInputBorder,
    colorWriteBarInputBorderAlpha = colorWriteBarInputBorderAlpha,
    colorTrackBackground = colorTrackBackground,
    colorTrackBuffer = colorTrackBuffer,
    colorSearchFieldBackground = colorSearchFieldBackground,
    colorPanelHeaderIcon = colorPanelHeaderIcon,
    colorSegmentedControl = colorSegmentedControl,
    colorTabbarTextInactive = colorTabbarTextInactive,
    colorTransparent = colorTransparent,
)
fun vkontakteAndroidDarkColorScheme(
    colorBackgroundAccent: Color = Color(0xFF529EF4),
    colorBackgroundAccentThemed: Color = Color(0xFFFFFFFF),
    colorBackgroundAccentThemedAlpha: Color = Color(0x33FFFFFF),
    colorBackgroundAccentTint: Color = Color(0xFF5A9EFF),
    colorBackgroundAccentAlternative: Color = Color(0xFF529EF4),
    colorBackground: Color = Color(0xFF0A0A0A),
    colorBackgroundContent: Color = Color(0xFF19191A),
    colorBackgroundContentAlpha: Color = Color(0xCC19191A),
    colorBackgroundContentInverse: Color = Color(0xFFFFFFFF),
    colorBackgroundSecondary: Color = Color(0xFF232324),
    colorBackgroundSecondaryAlpha: Color = Color(0x19FFFFFF),
    colorBackgroundTertiary: Color = Color(0xFF202021),
    colorBackgroundTertiaryAlpha: Color = Color(0x07FFFFFF),
    colorBackgroundContrast: Color = Color(0xFFFFFFFF),
    colorBackgroundContrastSecondaryAlpha: Color = Color(0x33FFFFFF),
    colorBackgroundContrastInverse: Color = Color(0xFF2C2D2E),
    colorBackgroundContrastThemed: Color = Color(0xFF2C2D2E),
    colorBackgroundModal: Color = Color(0xFF1C1D1E),
    colorBackgroundModalInverse: Color = Color(0xFFFFFFFF),
    colorBackgroundPositive: Color = Color(0xFF4BB34B),
    colorBackgroundPositiveTint: Color = Color(0xFF2E3E2B),
    colorBackgroundWarning: Color = Color(0xFF473315),
    colorBackgroundNegative: Color = Color(0xFFFF5C5C),
    colorBackgroundNegativeTint: Color = Color(0xFF522E2E),
    colorBackgroundInfoTint: Color = Color(0xFF1C3954),
    colorFieldBackground: Color = Color(0xFF232324),
    colorHeaderBackground: Color = Color(0xFF19191A),
    colorTextAccent: Color = Color(0xFF529EF4),
    colorTextAccentThemed: Color = Color(0xFFFFFFFF),
    colorTextPrimary: Color = Color(0xFFE1E3E6),
    colorTextPrimaryAlpha: Color = Color(0xB7F9FCFF),
    colorTextPrimaryInvariably: Color = Color(0xFF000000),
    colorTextSecondary: Color = Color(0xFF76787A),
    colorTextSecondaryAlpha: Color = Color(0x6BF7FBFF),
    colorTextSubhead: Color = Color(0xFF969A9F),
    colorTextTertiary: Color = Color(0xFF5D5F61),
    colorTextContrast: Color = Color(0xFFFFFFFF),
    colorTextContrastThemed: Color = Color(0xFF000000),
    colorTextPositive: Color = Color(0xFF4BB34B),
    colorTextNegative: Color = Color(0xFFFF5C5C),
    colorTextLink: Color = Color(0xFF529EF4),
    colorTextLinkThemed: Color = Color(0xFFFFFFFF),
    colorTextLinkTint: Color = Color(0xFF71AAEB),
    colorTextLinkVisited: Color = Color(0xFF4986CC),
    colorTextMuted: Color = Color(0xFFE1E3E6),
    colorLinkContrast: Color = Color(0xFFFFFFFF),
    colorIconAccent: Color = Color(0xFF529EF4),
    colorIconAccentThemed: Color = Color(0xFFFFFFFF),
    colorIconPrimary: Color = Color(0xFFE1E3E6),
    colorIconPrimaryInvariably: Color = Color(0xFF2C2D2E),
    colorIconMedium: Color = Color(0xFFB0B1B6),
    colorIconMediumAlpha: Color = Color(0xA8F1F7FF),
    colorIconSecondary: Color = Color(0xFF76787A),
    colorIconSecondaryAlpha: Color = Color(0x6DF1F7FF),
    colorIconTertiary: Color = Color(0xFF5D5F61),
    colorIconTertiaryAlpha: Color = Color(0x4CFFFFFF),
    colorIconContrast: Color = Color(0xFFFFFFFF),
    colorIconContrastThemed: Color = Color(0xFF000000),
    colorIconContrastSecondary: Color = Color(0xFFF2F3F5),
    colorIconPositive: Color = Color(0xFF4BB34B),
    colorIconWarning: Color = Color(0xFFEDB055),
    colorIconNegative: Color = Color(0xFFFF5C5C),
    colorStrokeAccent: Color = Color(0xFF529EF4),
    colorStrokeAccentThemed: Color = Color(0xFFFFFFFF),
    colorSeparatorPrimary: Color = Color(0xFF363738),
    colorSeparatorPrimary2x: Color = Color(0xFF444546),
    colorSeparatorPrimary3x: Color = Color(0xFF505253),
    colorSeparatorPrimaryAlpha: Color = Color(0x1EFFFFFF),
    colorSeparatorSecondary: Color = Color(0xFF141415),
    colorStrokePositive: Color = Color(0xFF4BB34B),
    colorStrokeNegative: Color = Color(0xFFFF5C5C),
    colorStrokeContrast: Color = Color(0xFFFFFFFF),
    colorStrokePrimary: Color = Color(0xFFE1E3E6),
    colorImageBorderAlpha: Color = Color(0x14FFFFFF),
    colorFieldBorderAlpha: Color = Color(0x1EFFFFFF),
    colorAccentBlue: Color = Color(0xFF71AAEB),
    colorAccentGray: Color = Color(0xFFA3ADB8),
    colorAccentRed: Color = Color(0xFFFF3347),
    colorAccentOrangeFire: Color = Color(0xFFF05C44),
    colorAccentOrange: Color = Color(0xFFFFA000),
    colorAccentOrangePeach: Color = Color(0xFFFFC062),
    colorAccentLime: Color = Color(0xFFAFF70D),
    colorAccentGreen: Color = Color(0xFF4BB34B),
    colorAccentCyan: Color = Color(0xFF13FFD0),
    colorAccentAzure: Color = Color(0xFF0077FF),
    colorAccentPurple: Color = Color(0xFF9985FF),
    colorAccentViolet: Color = Color(0xFFA94FFF),
    colorAccentRaspberryPink: Color = Color(0xFFF060C0),
    colorAccentPink: Color = Color(0xFFF45FFF),
    colorAccentSecondary: Color = Color(0xFF3F8AE0),
    colorOverlayPrimary: Color = Color(0x66000000),
    colorOverlaySecondary: Color = Color(0x44000000),
    colorAvatarOverlay: Color = Color(0x99000000),
    colorAvatarOverlayInverseAlpha: Color = Color(0xD8FFFFFF),
    colorActionSheetText: Color = Color(0xFF71AAEB),
    colorImagePlaceholder: Color = Color(0xFF2A2B2C),
    colorImagePlaceholderAlpha: Color = Color(0x14F1F7FF),
    colorSkeletonFrom: Color = Color(0xFF232324),
    colorSkeletonTo: Color = Color(0xFF2C2D2E),
    colorButtonText: Color = Color(0xFFFFFFFF),
    colorButtonIcon: Color = Color(0xFFFFFFFF),
    colorButtonStroke: Color = Color(0xFFFFFFFF),
    colorWriteBarIcon: Color = Color(0xFF76787A),
    colorWriteBarInputBackground: Color = Color(0xFF2C2D2E),
    colorWriteBarInputBorder: Color = Color(0xFF2C2D2E),
    colorWriteBarInputBorderAlpha: Color = Color(0xCCFFFFFF),
    colorTrackBackground: Color = Color(0xFF454647),
    colorTrackBuffer: Color = Color(0xFF405772),
    colorSearchFieldBackground: Color = Color(0xFF363738),
    colorPanelHeaderIcon: Color = Color(0xFF71AAEB),
    colorSegmentedControl: Color = Color(0xFF626364),
    colorTabbarTextInactive: Color = Color(0xFF76787A),
    colorTransparent: Color = Color(0x00000000),
) = VkColorScheme(
    colorBackgroundAccent = colorBackgroundAccent,
    colorBackgroundAccentThemed = colorBackgroundAccentThemed,
    colorBackgroundAccentThemedAlpha = colorBackgroundAccentThemedAlpha,
    colorBackgroundAccentTint = colorBackgroundAccentTint,
    colorBackgroundAccentAlternative = colorBackgroundAccentAlternative,
    colorBackground = colorBackground,
    colorBackgroundContent = colorBackgroundContent,
    colorBackgroundContentAlpha = colorBackgroundContentAlpha,
    colorBackgroundContentInverse = colorBackgroundContentInverse,
    colorBackgroundSecondary = colorBackgroundSecondary,
    colorBackgroundSecondaryAlpha = colorBackgroundSecondaryAlpha,
    colorBackgroundTertiary = colorBackgroundTertiary,
    colorBackgroundTertiaryAlpha = colorBackgroundTertiaryAlpha,
    colorBackgroundContrast = colorBackgroundContrast,
    colorBackgroundContrastSecondaryAlpha = colorBackgroundContrastSecondaryAlpha,
    colorBackgroundContrastInverse = colorBackgroundContrastInverse,
    colorBackgroundContrastThemed = colorBackgroundContrastThemed,
    colorBackgroundModal = colorBackgroundModal,
    colorBackgroundModalInverse = colorBackgroundModalInverse,
    colorBackgroundPositive = colorBackgroundPositive,
    colorBackgroundPositiveTint = colorBackgroundPositiveTint,
    colorBackgroundWarning = colorBackgroundWarning,
    colorBackgroundNegative = colorBackgroundNegative,
    colorBackgroundNegativeTint = colorBackgroundNegativeTint,
    colorBackgroundInfoTint = colorBackgroundInfoTint,
    colorFieldBackground = colorFieldBackground,
    colorHeaderBackground = colorHeaderBackground,
    colorTextAccent = colorTextAccent,
    colorTextAccentThemed = colorTextAccentThemed,
    colorTextPrimary = colorTextPrimary,
    colorTextPrimaryAlpha = colorTextPrimaryAlpha,
    colorTextPrimaryInvariably = colorTextPrimaryInvariably,
    colorTextSecondary = colorTextSecondary,
    colorTextSecondaryAlpha = colorTextSecondaryAlpha,
    colorTextSubhead = colorTextSubhead,
    colorTextTertiary = colorTextTertiary,
    colorTextContrast = colorTextContrast,
    colorTextContrastThemed = colorTextContrastThemed,
    colorTextPositive = colorTextPositive,
    colorTextNegative = colorTextNegative,
    colorTextLink = colorTextLink,
    colorTextLinkThemed = colorTextLinkThemed,
    colorTextLinkTint = colorTextLinkTint,
    colorTextLinkVisited = colorTextLinkVisited,
    colorTextMuted = colorTextMuted,
    colorLinkContrast = colorLinkContrast,
    colorIconAccent = colorIconAccent,
    colorIconAccentThemed = colorIconAccentThemed,
    colorIconPrimary = colorIconPrimary,
    colorIconPrimaryInvariably = colorIconPrimaryInvariably,
    colorIconMedium = colorIconMedium,
    colorIconMediumAlpha = colorIconMediumAlpha,
    colorIconSecondary = colorIconSecondary,
    colorIconSecondaryAlpha = colorIconSecondaryAlpha,
    colorIconTertiary = colorIconTertiary,
    colorIconTertiaryAlpha = colorIconTertiaryAlpha,
    colorIconContrast = colorIconContrast,
    colorIconContrastThemed = colorIconContrastThemed,
    colorIconContrastSecondary = colorIconContrastSecondary,
    colorIconPositive = colorIconPositive,
    colorIconWarning = colorIconWarning,
    colorIconNegative = colorIconNegative,
    colorStrokeAccent = colorStrokeAccent,
    colorStrokeAccentThemed = colorStrokeAccentThemed,
    colorSeparatorPrimary = colorSeparatorPrimary,
    colorSeparatorPrimary2x = colorSeparatorPrimary2x,
    colorSeparatorPrimary3x = colorSeparatorPrimary3x,
    colorSeparatorPrimaryAlpha = colorSeparatorPrimaryAlpha,
    colorSeparatorSecondary = colorSeparatorSecondary,
    colorStrokePositive = colorStrokePositive,
    colorStrokeNegative = colorStrokeNegative,
    colorStrokeContrast = colorStrokeContrast,
    colorStrokePrimary = colorStrokePrimary,
    colorImageBorderAlpha = colorImageBorderAlpha,
    colorFieldBorderAlpha = colorFieldBorderAlpha,
    colorAccentBlue = colorAccentBlue,
    colorAccentGray = colorAccentGray,
    colorAccentRed = colorAccentRed,
    colorAccentOrangeFire = colorAccentOrangeFire,
    colorAccentOrange = colorAccentOrange,
    colorAccentOrangePeach = colorAccentOrangePeach,
    colorAccentLime = colorAccentLime,
    colorAccentGreen = colorAccentGreen,
    colorAccentCyan = colorAccentCyan,
    colorAccentAzure = colorAccentAzure,
    colorAccentPurple = colorAccentPurple,
    colorAccentViolet = colorAccentViolet,
    colorAccentRaspberryPink = colorAccentRaspberryPink,
    colorAccentPink = colorAccentPink,
    colorAccentSecondary = colorAccentSecondary,
    colorOverlayPrimary = colorOverlayPrimary,
    colorOverlaySecondary = colorOverlaySecondary,
    colorAvatarOverlay = colorAvatarOverlay,
    colorAvatarOverlayInverseAlpha = colorAvatarOverlayInverseAlpha,
    colorActionSheetText = colorActionSheetText,
    colorImagePlaceholder = colorImagePlaceholder,
    colorImagePlaceholderAlpha = colorImagePlaceholderAlpha,
    colorSkeletonFrom = colorSkeletonFrom,
    colorSkeletonTo = colorSkeletonTo,
    colorButtonText = colorButtonText,
    colorButtonIcon = colorButtonIcon,
    colorButtonStroke = colorButtonStroke,
    colorWriteBarIcon = colorWriteBarIcon,
    colorWriteBarInputBackground = colorWriteBarInputBackground,
    colorWriteBarInputBorder = colorWriteBarInputBorder,
    colorWriteBarInputBorderAlpha = colorWriteBarInputBorderAlpha,
    colorTrackBackground = colorTrackBackground,
    colorTrackBuffer = colorTrackBuffer,
    colorSearchFieldBackground = colorSearchFieldBackground,
    colorPanelHeaderIcon = colorPanelHeaderIcon,
    colorSegmentedControl = colorSegmentedControl,
    colorTabbarTextInactive = colorTabbarTextInactive,
    colorTransparent = colorTransparent,
)
