package com.vkui.theme

import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import androidx.compose.runtime.Immutable

@Immutable
class VkDimens(
    val sizeSelectIconPadding: Dp,
    val sizePopupBasePadding: Dp,
    val sizePopupHeaderPadding: Dp,
    val sizeLabelHorizontalMargin: Dp,
    val sizeBorderRadius: Dp,
    val sizeBorderRadiusRounded: Dp,
    val sizeCheckBorderRadius: Dp,
    val sizeBorderRadiusPaper: Dp,
    val sizeBorderRadiusPromo: Dp,
    val sizeCellHeight: Dp,
    val sizeFieldHeight: Dp,
    val sizeSearchHeight: Dp,
    val sizeButtonExtraSmallHeight: Dp,
    val sizeButtonSmallHeight: Dp,
    val sizeButtonMediumHeight: Dp,
    val sizeButtonLargeHeight: Dp,
    val sizeCheckbox: Dp,
    val sizeArrow: Dp,
    val sizeArrowPromo: Dp,
    val sizePopupSmall: Dp,
    val sizePopupMedium: Dp,
    val sizePopupLarge: Dp,
    val sizeFieldHorizontalPadding: Dp,
    val sizeButtonPaddingHorizontal: Dp,
    val sizeArrowPadding: Dp,
    val sizeTooltipMargin: Dp,
    val sizeIconUI: Dp,
    val sizeAvatarXS: Dp,
    val sizeAvatarS: Dp,
    val sizeAvatarM: Dp,
    val sizeAvatarL: Dp,
    val sizeAvatarXL: Dp,
    val sizeBadgeXS: Dp,
    val sizeBadgeS: Dp,
    val sizeBadgeM: Dp,
    val sizeBadgeL: Dp,
    val sizeBadgeXL: Dp,
    val sizeCardgridPadding: Dp,
    val sizeCardBorderRadius: Dp,
    val sizeCardgridPaddingVertical: Dp,
    val sizeBasePaddingHorizontal: Dp,
    val sizeBasePaddingVertical: Dp,
    val sizeButtonGroupGapSpace: Dp,
    val sizeButtonGroupGapSmall: Dp,
    val sizeButtonGroupGapMedium: Dp,
    val sizeOptionHierarchy: Dp,
    val sizeSwitchHeight: Dp,
    val sizeSwitchWidth: Dp,
    val sizeSwitchPin: Dp,
    val sizePanelHeaderHeight: Dp,
    val sizeButtonBaseSmallPaddingHorizontal: Dp,
    val sizeButtonBaseMediumPaddingHorizontal: Dp,
    val sizeButtonBaseLargePaddingHorizontal: Dp,
    val sizeButtonBaseSmallPaddingHorizontalIcon: Dp,
    val sizeButtonBaseMediumPaddingHorizontalIcon: Dp,
    val sizeButtonBaseLargePaddingHorizontalIcon: Dp,
    val sizeButtonTertiarySmallPaddingHorizontal: Dp,
    val sizeButtonTertiaryMediumPaddingHorizontal: Dp,
    val sizeButtonTertiaryLargePaddingHorizontal: Dp,
    val sizeButtonTertiarySmallPaddingHorizontalIcon: Dp,
    val sizeButtonTertiaryMediumPaddingHorizontalIcon: Dp,
    val sizeButtonTertiaryLargePaddingHorizontalIcon: Dp,
    val sizeButtonMinimumWidth: Dp,
    val sizeFormItemPaddingVertical: Dp,
    val sizeSplitColPaddingHorizontal: Dp,
    val sizeSubnavigationBarGap: Dp,
    val sizeSubnavigationBarPaddingVertical: Dp,
    val sizeBorder1x: Dp,
    val sizeBorder2x: Dp,
    val sizeBorder3x: Dp,
    val spacingSize3Xs: Dp,
    val spacingSize2Xs: Dp,
    val spacingSizeXs: Dp,
    val spacingSizeS: Dp,
    val spacingSizeM: Dp,
    val spacingSizeL: Dp,
    val spacingSizeXl: Dp,
    val spacingSize2Xl: Dp,
    val spacingSize3Xl: Dp,
    val spacingSize4Xl: Dp,
)

fun vkontakteAndroidDimens(
    sizeSelectIconPadding: Dp = 6.0.dp,
    sizePopupBasePadding: Dp = 32.0.dp,
    sizePopupHeaderPadding: Dp = 24.0.dp,
    sizeLabelHorizontalMargin: Dp = 16.0.dp,
    sizeBorderRadius: Dp = 8.0.dp,
    sizeBorderRadiusRounded: Dp = 48.0.dp,
    sizeCheckBorderRadius: Dp = 4.0.dp,
    sizeBorderRadiusPaper: Dp = 12.0.dp,
    sizeBorderRadiusPromo: Dp = 20.0.dp,
    sizeCellHeight: Dp = 48.0.dp,
    sizeFieldHeight: Dp = 44.0.dp,
    sizeSearchHeight: Dp = 36.0.dp,
    sizeButtonExtraSmallHeight: Dp = 24.0.dp,
    sizeButtonSmallHeight: Dp = 30.0.dp,
    sizeButtonMediumHeight: Dp = 36.0.dp,
    sizeButtonLargeHeight: Dp = 44.0.dp,
    sizeCheckbox: Dp = 16.0.dp,
    sizeArrow: Dp = 8.0.dp,
    sizeArrowPromo: Dp = 40.0.dp,
    sizePopupSmall: Dp = 430.0.dp,
    sizePopupMedium: Dp = 680.0.dp,
    sizePopupLarge: Dp = 880.0.dp,
    sizeFieldHorizontalPadding: Dp = 12.0.dp,
    sizeButtonPaddingHorizontal: Dp = 12.0.dp,
    sizeArrowPadding: Dp = 12.0.dp,
    sizeTooltipMargin: Dp = 8.0.dp,
    sizeIconUI: Dp = 16.0.dp,
    sizeAvatarXS: Dp = 24.0.dp,
    sizeAvatarS: Dp = 32.0.dp,
    sizeAvatarM: Dp = 48.0.dp,
    sizeAvatarL: Dp = 96.0.dp,
    sizeAvatarXL: Dp = 128.0.dp,
    sizeBadgeXS: Dp = 12.0.dp,
    sizeBadgeS: Dp = 16.0.dp,
    sizeBadgeM: Dp = 24.0.dp,
    sizeBadgeL: Dp = 44.0.dp,
    sizeBadgeXL: Dp = 56.0.dp,
    sizeCardgridPadding: Dp = 8.0.dp,
    sizeCardBorderRadius: Dp = 8.0.dp,
    sizeCardgridPaddingVertical: Dp = 8.0.dp,
    sizeBasePaddingHorizontal: Dp = 16.0.dp,
    sizeBasePaddingVertical: Dp = 12.0.dp,
    sizeButtonGroupGapSpace: Dp = 1.0.dp,
    sizeButtonGroupGapSmall: Dp = 8.0.dp,
    sizeButtonGroupGapMedium: Dp = 12.0.dp,
    sizeOptionHierarchy: Dp = 32.0.dp,
    sizeSwitchHeight: Dp = 14.0.dp,
    sizeSwitchWidth: Dp = 34.0.dp,
    sizeSwitchPin: Dp = 20.0.dp,
    sizePanelHeaderHeight: Dp = 56.0.dp,
    sizeButtonBaseSmallPaddingHorizontal: Dp = 16.0.dp,
    sizeButtonBaseMediumPaddingHorizontal: Dp = 16.0.dp,
    sizeButtonBaseLargePaddingHorizontal: Dp = 20.0.dp,
    sizeButtonBaseSmallPaddingHorizontalIcon: Dp = 12.0.dp,
    sizeButtonBaseMediumPaddingHorizontalIcon: Dp = 12.0.dp,
    sizeButtonBaseLargePaddingHorizontalIcon: Dp = 16.0.dp,
    sizeButtonTertiarySmallPaddingHorizontal: Dp = 12.0.dp,
    sizeButtonTertiaryMediumPaddingHorizontal: Dp = 12.0.dp,
    sizeButtonTertiaryLargePaddingHorizontal: Dp = 16.0.dp,
    sizeButtonTertiarySmallPaddingHorizontalIcon: Dp = 8.0.dp,
    sizeButtonTertiaryMediumPaddingHorizontalIcon: Dp = 8.0.dp,
    sizeButtonTertiaryLargePaddingHorizontalIcon: Dp = 12.0.dp,
    sizeButtonMinimumWidth: Dp = 80.0.dp,
    sizeFormItemPaddingVertical: Dp = 12.0.dp,
    sizeSplitColPaddingHorizontal: Dp = 16.0.dp,
    sizeSubnavigationBarGap: Dp = 8.0.dp,
    sizeSubnavigationBarPaddingVertical: Dp = 12.0.dp,
    sizeBorder1x: Dp = 1.0.dp,
    sizeBorder2x: Dp = 0.5.dp,
    sizeBorder3x: Dp = 0.33.dp,
    spacingSize3Xs: Dp = 2.dp,
    spacingSize2Xs: Dp = 2.dp,
    spacingSizeXs: Dp = 4.dp,
    spacingSizeS: Dp = 6.dp,
    spacingSizeM: Dp = 8.dp,
    spacingSizeL: Dp = 10.dp,
    spacingSizeXl: Dp = 12.dp,
    spacingSize2Xl: Dp = 16.dp,
    spacingSize3Xl: Dp = 20.dp,
    spacingSize4Xl: Dp = 24.dp,
) = VkDimens(
    sizeSelectIconPadding = sizeSelectIconPadding,
    sizePopupBasePadding = sizePopupBasePadding,
    sizePopupHeaderPadding = sizePopupHeaderPadding,
    sizeLabelHorizontalMargin = sizeLabelHorizontalMargin,
    sizeBorderRadius = sizeBorderRadius,
    sizeBorderRadiusRounded = sizeBorderRadiusRounded,
    sizeCheckBorderRadius = sizeCheckBorderRadius,
    sizeBorderRadiusPaper = sizeBorderRadiusPaper,
    sizeBorderRadiusPromo = sizeBorderRadiusPromo,
    sizeCellHeight = sizeCellHeight,
    sizeFieldHeight = sizeFieldHeight,
    sizeSearchHeight = sizeSearchHeight,
    sizeButtonExtraSmallHeight = sizeButtonExtraSmallHeight,
    sizeButtonSmallHeight = sizeButtonSmallHeight,
    sizeButtonMediumHeight = sizeButtonMediumHeight,
    sizeButtonLargeHeight = sizeButtonLargeHeight,
    sizeCheckbox = sizeCheckbox,
    sizeArrow = sizeArrow,
    sizeArrowPromo = sizeArrowPromo,
    sizePopupSmall = sizePopupSmall,
    sizePopupMedium = sizePopupMedium,
    sizePopupLarge = sizePopupLarge,
    sizeFieldHorizontalPadding = sizeFieldHorizontalPadding,
    sizeButtonPaddingHorizontal = sizeButtonPaddingHorizontal,
    sizeArrowPadding = sizeArrowPadding,
    sizeTooltipMargin = sizeTooltipMargin,
    sizeIconUI = sizeIconUI,
    sizeAvatarXS = sizeAvatarXS,
    sizeAvatarS = sizeAvatarS,
    sizeAvatarM = sizeAvatarM,
    sizeAvatarL = sizeAvatarL,
    sizeAvatarXL = sizeAvatarXL,
    sizeBadgeXS = sizeBadgeXS,
    sizeBadgeS = sizeBadgeS,
    sizeBadgeM = sizeBadgeM,
    sizeBadgeL = sizeBadgeL,
    sizeBadgeXL = sizeBadgeXL,
    sizeCardgridPadding = sizeCardgridPadding,
    sizeCardBorderRadius = sizeCardBorderRadius,
    sizeCardgridPaddingVertical = sizeCardgridPaddingVertical,
    sizeBasePaddingHorizontal = sizeBasePaddingHorizontal,
    sizeBasePaddingVertical = sizeBasePaddingVertical,
    sizeButtonGroupGapSpace = sizeButtonGroupGapSpace,
    sizeButtonGroupGapSmall = sizeButtonGroupGapSmall,
    sizeButtonGroupGapMedium = sizeButtonGroupGapMedium,
    sizeOptionHierarchy = sizeOptionHierarchy,
    sizeSwitchHeight = sizeSwitchHeight,
    sizeSwitchWidth = sizeSwitchWidth,
    sizeSwitchPin = sizeSwitchPin,
    sizePanelHeaderHeight = sizePanelHeaderHeight,
    sizeButtonBaseSmallPaddingHorizontal = sizeButtonBaseSmallPaddingHorizontal,
    sizeButtonBaseMediumPaddingHorizontal = sizeButtonBaseMediumPaddingHorizontal,
    sizeButtonBaseLargePaddingHorizontal = sizeButtonBaseLargePaddingHorizontal,
    sizeButtonBaseSmallPaddingHorizontalIcon = sizeButtonBaseSmallPaddingHorizontalIcon,
    sizeButtonBaseMediumPaddingHorizontalIcon = sizeButtonBaseMediumPaddingHorizontalIcon,
    sizeButtonBaseLargePaddingHorizontalIcon = sizeButtonBaseLargePaddingHorizontalIcon,
    sizeButtonTertiarySmallPaddingHorizontal = sizeButtonTertiarySmallPaddingHorizontal,
    sizeButtonTertiaryMediumPaddingHorizontal = sizeButtonTertiaryMediumPaddingHorizontal,
    sizeButtonTertiaryLargePaddingHorizontal = sizeButtonTertiaryLargePaddingHorizontal,
    sizeButtonTertiarySmallPaddingHorizontalIcon = sizeButtonTertiarySmallPaddingHorizontalIcon,
    sizeButtonTertiaryMediumPaddingHorizontalIcon = sizeButtonTertiaryMediumPaddingHorizontalIcon,
    sizeButtonTertiaryLargePaddingHorizontalIcon = sizeButtonTertiaryLargePaddingHorizontalIcon,
    sizeButtonMinimumWidth = sizeButtonMinimumWidth,
    sizeFormItemPaddingVertical = sizeFormItemPaddingVertical,
    sizeSplitColPaddingHorizontal = sizeSplitColPaddingHorizontal,
    sizeSubnavigationBarGap = sizeSubnavigationBarGap,
    sizeSubnavigationBarPaddingVertical = sizeSubnavigationBarPaddingVertical,
    sizeBorder1x = sizeBorder1x,
    sizeBorder2x = sizeBorder2x,
    sizeBorder3x = sizeBorder3x,
    spacingSize3Xs = spacingSize3Xs,
    spacingSize2Xs = spacingSize2Xs,
    spacingSizeXs = spacingSizeXs,
    spacingSizeS = spacingSizeS,
    spacingSizeM = spacingSizeM,
    spacingSizeL = spacingSizeL,
    spacingSizeXl = spacingSizeXl,
    spacingSize2Xl = spacingSize2Xl,
    spacingSize3Xl = spacingSize3Xl,
    spacingSize4Xl = spacingSize4Xl,
)
fun vkontakteAndroidDarkDimens(
    sizeSelectIconPadding: Dp = 6.0.dp,
    sizePopupBasePadding: Dp = 32.0.dp,
    sizePopupHeaderPadding: Dp = 24.0.dp,
    sizeLabelHorizontalMargin: Dp = 16.0.dp,
    sizeBorderRadius: Dp = 8.0.dp,
    sizeBorderRadiusRounded: Dp = 48.0.dp,
    sizeCheckBorderRadius: Dp = 4.0.dp,
    sizeBorderRadiusPaper: Dp = 12.0.dp,
    sizeBorderRadiusPromo: Dp = 20.0.dp,
    sizeCellHeight: Dp = 48.0.dp,
    sizeFieldHeight: Dp = 44.0.dp,
    sizeSearchHeight: Dp = 36.0.dp,
    sizeButtonExtraSmallHeight: Dp = 24.0.dp,
    sizeButtonSmallHeight: Dp = 30.0.dp,
    sizeButtonMediumHeight: Dp = 36.0.dp,
    sizeButtonLargeHeight: Dp = 44.0.dp,
    sizeCheckbox: Dp = 16.0.dp,
    sizeArrow: Dp = 8.0.dp,
    sizeArrowPromo: Dp = 40.0.dp,
    sizePopupSmall: Dp = 430.0.dp,
    sizePopupMedium: Dp = 680.0.dp,
    sizePopupLarge: Dp = 880.0.dp,
    sizeFieldHorizontalPadding: Dp = 12.0.dp,
    sizeButtonPaddingHorizontal: Dp = 12.0.dp,
    sizeArrowPadding: Dp = 12.0.dp,
    sizeTooltipMargin: Dp = 8.0.dp,
    sizeIconUI: Dp = 16.0.dp,
    sizeAvatarXS: Dp = 24.0.dp,
    sizeAvatarS: Dp = 32.0.dp,
    sizeAvatarM: Dp = 48.0.dp,
    sizeAvatarL: Dp = 96.0.dp,
    sizeAvatarXL: Dp = 128.0.dp,
    sizeBadgeXS: Dp = 12.0.dp,
    sizeBadgeS: Dp = 16.0.dp,
    sizeBadgeM: Dp = 24.0.dp,
    sizeBadgeL: Dp = 44.0.dp,
    sizeBadgeXL: Dp = 56.0.dp,
    sizeCardgridPadding: Dp = 8.0.dp,
    sizeCardBorderRadius: Dp = 8.0.dp,
    sizeCardgridPaddingVertical: Dp = 8.0.dp,
    sizeBasePaddingHorizontal: Dp = 16.0.dp,
    sizeBasePaddingVertical: Dp = 12.0.dp,
    sizeButtonGroupGapSpace: Dp = 1.0.dp,
    sizeButtonGroupGapSmall: Dp = 8.0.dp,
    sizeButtonGroupGapMedium: Dp = 12.0.dp,
    sizeOptionHierarchy: Dp = 32.0.dp,
    sizeSwitchHeight: Dp = 14.0.dp,
    sizeSwitchWidth: Dp = 34.0.dp,
    sizeSwitchPin: Dp = 20.0.dp,
    sizePanelHeaderHeight: Dp = 56.0.dp,
    sizeButtonBaseSmallPaddingHorizontal: Dp = 16.0.dp,
    sizeButtonBaseMediumPaddingHorizontal: Dp = 16.0.dp,
    sizeButtonBaseLargePaddingHorizontal: Dp = 20.0.dp,
    sizeButtonBaseSmallPaddingHorizontalIcon: Dp = 12.0.dp,
    sizeButtonBaseMediumPaddingHorizontalIcon: Dp = 12.0.dp,
    sizeButtonBaseLargePaddingHorizontalIcon: Dp = 16.0.dp,
    sizeButtonTertiarySmallPaddingHorizontal: Dp = 12.0.dp,
    sizeButtonTertiaryMediumPaddingHorizontal: Dp = 12.0.dp,
    sizeButtonTertiaryLargePaddingHorizontal: Dp = 16.0.dp,
    sizeButtonTertiarySmallPaddingHorizontalIcon: Dp = 8.0.dp,
    sizeButtonTertiaryMediumPaddingHorizontalIcon: Dp = 8.0.dp,
    sizeButtonTertiaryLargePaddingHorizontalIcon: Dp = 12.0.dp,
    sizeButtonMinimumWidth: Dp = 80.0.dp,
    sizeFormItemPaddingVertical: Dp = 12.0.dp,
    sizeSplitColPaddingHorizontal: Dp = 16.0.dp,
    sizeSubnavigationBarGap: Dp = 8.0.dp,
    sizeSubnavigationBarPaddingVertical: Dp = 12.0.dp,
    sizeBorder1x: Dp = 1.0.dp,
    sizeBorder2x: Dp = 0.5.dp,
    sizeBorder3x: Dp = 0.33.dp,
    spacingSize3Xs: Dp = 2.dp,
    spacingSize2Xs: Dp = 2.dp,
    spacingSizeXs: Dp = 4.dp,
    spacingSizeS: Dp = 6.dp,
    spacingSizeM: Dp = 8.dp,
    spacingSizeL: Dp = 10.dp,
    spacingSizeXl: Dp = 12.dp,
    spacingSize2Xl: Dp = 16.dp,
    spacingSize3Xl: Dp = 20.dp,
    spacingSize4Xl: Dp = 24.dp,
) = VkDimens(
    sizeSelectIconPadding = sizeSelectIconPadding,
    sizePopupBasePadding = sizePopupBasePadding,
    sizePopupHeaderPadding = sizePopupHeaderPadding,
    sizeLabelHorizontalMargin = sizeLabelHorizontalMargin,
    sizeBorderRadius = sizeBorderRadius,
    sizeBorderRadiusRounded = sizeBorderRadiusRounded,
    sizeCheckBorderRadius = sizeCheckBorderRadius,
    sizeBorderRadiusPaper = sizeBorderRadiusPaper,
    sizeBorderRadiusPromo = sizeBorderRadiusPromo,
    sizeCellHeight = sizeCellHeight,
    sizeFieldHeight = sizeFieldHeight,
    sizeSearchHeight = sizeSearchHeight,
    sizeButtonExtraSmallHeight = sizeButtonExtraSmallHeight,
    sizeButtonSmallHeight = sizeButtonSmallHeight,
    sizeButtonMediumHeight = sizeButtonMediumHeight,
    sizeButtonLargeHeight = sizeButtonLargeHeight,
    sizeCheckbox = sizeCheckbox,
    sizeArrow = sizeArrow,
    sizeArrowPromo = sizeArrowPromo,
    sizePopupSmall = sizePopupSmall,
    sizePopupMedium = sizePopupMedium,
    sizePopupLarge = sizePopupLarge,
    sizeFieldHorizontalPadding = sizeFieldHorizontalPadding,
    sizeButtonPaddingHorizontal = sizeButtonPaddingHorizontal,
    sizeArrowPadding = sizeArrowPadding,
    sizeTooltipMargin = sizeTooltipMargin,
    sizeIconUI = sizeIconUI,
    sizeAvatarXS = sizeAvatarXS,
    sizeAvatarS = sizeAvatarS,
    sizeAvatarM = sizeAvatarM,
    sizeAvatarL = sizeAvatarL,
    sizeAvatarXL = sizeAvatarXL,
    sizeBadgeXS = sizeBadgeXS,
    sizeBadgeS = sizeBadgeS,
    sizeBadgeM = sizeBadgeM,
    sizeBadgeL = sizeBadgeL,
    sizeBadgeXL = sizeBadgeXL,
    sizeCardgridPadding = sizeCardgridPadding,
    sizeCardBorderRadius = sizeCardBorderRadius,
    sizeCardgridPaddingVertical = sizeCardgridPaddingVertical,
    sizeBasePaddingHorizontal = sizeBasePaddingHorizontal,
    sizeBasePaddingVertical = sizeBasePaddingVertical,
    sizeButtonGroupGapSpace = sizeButtonGroupGapSpace,
    sizeButtonGroupGapSmall = sizeButtonGroupGapSmall,
    sizeButtonGroupGapMedium = sizeButtonGroupGapMedium,
    sizeOptionHierarchy = sizeOptionHierarchy,
    sizeSwitchHeight = sizeSwitchHeight,
    sizeSwitchWidth = sizeSwitchWidth,
    sizeSwitchPin = sizeSwitchPin,
    sizePanelHeaderHeight = sizePanelHeaderHeight,
    sizeButtonBaseSmallPaddingHorizontal = sizeButtonBaseSmallPaddingHorizontal,
    sizeButtonBaseMediumPaddingHorizontal = sizeButtonBaseMediumPaddingHorizontal,
    sizeButtonBaseLargePaddingHorizontal = sizeButtonBaseLargePaddingHorizontal,
    sizeButtonBaseSmallPaddingHorizontalIcon = sizeButtonBaseSmallPaddingHorizontalIcon,
    sizeButtonBaseMediumPaddingHorizontalIcon = sizeButtonBaseMediumPaddingHorizontalIcon,
    sizeButtonBaseLargePaddingHorizontalIcon = sizeButtonBaseLargePaddingHorizontalIcon,
    sizeButtonTertiarySmallPaddingHorizontal = sizeButtonTertiarySmallPaddingHorizontal,
    sizeButtonTertiaryMediumPaddingHorizontal = sizeButtonTertiaryMediumPaddingHorizontal,
    sizeButtonTertiaryLargePaddingHorizontal = sizeButtonTertiaryLargePaddingHorizontal,
    sizeButtonTertiarySmallPaddingHorizontalIcon = sizeButtonTertiarySmallPaddingHorizontalIcon,
    sizeButtonTertiaryMediumPaddingHorizontalIcon = sizeButtonTertiaryMediumPaddingHorizontalIcon,
    sizeButtonTertiaryLargePaddingHorizontalIcon = sizeButtonTertiaryLargePaddingHorizontalIcon,
    sizeButtonMinimumWidth = sizeButtonMinimumWidth,
    sizeFormItemPaddingVertical = sizeFormItemPaddingVertical,
    sizeSplitColPaddingHorizontal = sizeSplitColPaddingHorizontal,
    sizeSubnavigationBarGap = sizeSubnavigationBarGap,
    sizeSubnavigationBarPaddingVertical = sizeSubnavigationBarPaddingVertical,
    sizeBorder1x = sizeBorder1x,
    sizeBorder2x = sizeBorder2x,
    sizeBorder3x = sizeBorder3x,
    spacingSize3Xs = spacingSize3Xs,
    spacingSize2Xs = spacingSize2Xs,
    spacingSizeXs = spacingSizeXs,
    spacingSizeS = spacingSizeS,
    spacingSizeM = spacingSizeM,
    spacingSizeL = spacingSizeL,
    spacingSizeXl = spacingSizeXl,
    spacingSize2Xl = spacingSize2Xl,
    spacingSize3Xl = spacingSize3Xl,
    spacingSize4Xl = spacingSize4Xl,
)
