package com.vkui.theme

import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.sp
import androidx.compose.runtime.Immutable

@Immutable
class VkTypography(
    val fontDisplayTitle1: VkTextStyle,
    val fontDisplayTitle2: VkTextStyle,
    val fontDisplayTitle3: VkTextStyle,
    val fontDisplayTitle4: VkTextStyle,
    val fontTitle1: VkTextStyle,
    val fontTitle2: VkTextStyle,
    val fontTitle3: VkTextStyle,
    val fontHeadline1: VkTextStyle,
    val fontHeadline2: VkTextStyle,
    val fontText: VkTextStyle,
    val fontParagraph: VkTextStyle,
    val fontSubhead: VkTextStyle,
    val fontFootnote: VkTextStyle,
    val fontFootnoteCaps: VkTextStyle,
    val fontCaption1: VkTextStyle,
    val fontCaption1Caps: VkTextStyle,
    val fontCaption2: VkTextStyle,
    val fontCaption2Caps: VkTextStyle,
    val fontCaption3: VkTextStyle,
    val fontCaption3Caps: VkTextStyle,
    val fontHeadline: VkTextStyle,
)

fun vkontakteAndroidTypography(
    fontDisplayTitle1: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.NONE, textStyle = TextStyle(fontWeight = FontWeight(600), fontSize = 23.sp, lineHeight = 28.sp, letterSpacing = TextUnit.Unspecified, )),
    fontDisplayTitle2: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.NONE, textStyle = TextStyle(fontWeight = FontWeight(600), fontSize = 21.sp, lineHeight = 26.sp, letterSpacing = TextUnit.Unspecified, )),
    fontDisplayTitle3: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.NONE, textStyle = TextStyle(fontWeight = FontWeight(600), fontSize = 19.sp, lineHeight = 24.sp, letterSpacing = TextUnit.Unspecified, )),
    fontDisplayTitle4: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.NONE, textStyle = TextStyle(fontWeight = FontWeight(600), fontSize = 17.sp, lineHeight = 22.sp, letterSpacing = TextUnit.Unspecified, )),
    fontTitle1: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.NONE, textStyle = TextStyle(fontWeight = FontWeight(600), fontSize = 24.sp, lineHeight = 28.sp, letterSpacing = TextUnit.Unspecified, )),
    fontTitle2: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.NONE, textStyle = TextStyle(fontWeight = FontWeight(500), fontSize = 20.sp, lineHeight = 24.sp, letterSpacing = TextUnit.Unspecified, )),
    fontTitle3: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.NONE, textStyle = TextStyle(fontWeight = FontWeight(600), fontSize = 17.sp, lineHeight = 22.sp, letterSpacing = TextUnit.Unspecified, )),
    fontHeadline1: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.NONE, textStyle = TextStyle(fontWeight = FontWeight(500), fontSize = 16.sp, lineHeight = 20.sp, letterSpacing = 0.15.sp, )),
    fontHeadline2: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.NONE, textStyle = TextStyle(fontWeight = FontWeight(500), fontSize = 15.sp, lineHeight = 20.sp, letterSpacing = TextUnit.Unspecified, )),
    fontText: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.NONE, textStyle = TextStyle(fontWeight = FontWeight(400), fontSize = 16.sp, lineHeight = 20.sp, letterSpacing = 0.15.sp, )),
    fontParagraph: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.NONE, textStyle = TextStyle(fontWeight = FontWeight(400), fontSize = 15.sp, lineHeight = 20.sp, letterSpacing = TextUnit.Unspecified, )),
    fontSubhead: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.NONE, textStyle = TextStyle(fontWeight = FontWeight(400), fontSize = 14.sp, lineHeight = 18.sp, letterSpacing = 0.15.sp, )),
    fontFootnote: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.NONE, textStyle = TextStyle(fontWeight = FontWeight(400), fontSize = 13.sp, lineHeight = 16.sp, letterSpacing = 0.2.sp, )),
    fontFootnoteCaps: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.UPPERCASE, textStyle = TextStyle(fontWeight = FontWeight(600), fontSize = 13.sp, lineHeight = 16.sp, letterSpacing = 0.2.sp, )),
    fontCaption1: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.NONE, textStyle = TextStyle(fontWeight = FontWeight(400), fontSize = 12.sp, lineHeight = 14.sp, letterSpacing = 0.3.sp, )),
    fontCaption1Caps: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.UPPERCASE, textStyle = TextStyle(fontWeight = FontWeight(600), fontSize = 12.sp, lineHeight = 14.sp, letterSpacing = 0.3.sp, )),
    fontCaption2: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.NONE, textStyle = TextStyle(fontWeight = FontWeight(400), fontSize = 11.sp, lineHeight = 14.sp, letterSpacing = 0.3.sp, )),
    fontCaption2Caps: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.UPPERCASE, textStyle = TextStyle(fontWeight = FontWeight(600), fontSize = 11.sp, lineHeight = 14.sp, letterSpacing = 0.3.sp, )),
    fontCaption3: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.NONE, textStyle = TextStyle(fontWeight = FontWeight(400), fontSize = 9.sp, lineHeight = 12.sp, letterSpacing = 0.3.sp, )),
    fontCaption3Caps: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.UPPERCASE, textStyle = TextStyle(fontWeight = FontWeight(600), fontSize = 9.sp, lineHeight = 12.sp, letterSpacing = 0.3.sp, )),
    fontHeadline: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.NONE, textStyle = TextStyle(fontWeight = FontWeight(500), fontSize = 16.sp, lineHeight = 20.sp, letterSpacing = 0.15.sp, )),
) = VkTypography(
    fontDisplayTitle1 = fontDisplayTitle1,
    fontDisplayTitle2 = fontDisplayTitle2,
    fontDisplayTitle3 = fontDisplayTitle3,
    fontDisplayTitle4 = fontDisplayTitle4,
    fontTitle1 = fontTitle1,
    fontTitle2 = fontTitle2,
    fontTitle3 = fontTitle3,
    fontHeadline1 = fontHeadline1,
    fontHeadline2 = fontHeadline2,
    fontText = fontText,
    fontParagraph = fontParagraph,
    fontSubhead = fontSubhead,
    fontFootnote = fontFootnote,
    fontFootnoteCaps = fontFootnoteCaps,
    fontCaption1 = fontCaption1,
    fontCaption1Caps = fontCaption1Caps,
    fontCaption2 = fontCaption2,
    fontCaption2Caps = fontCaption2Caps,
    fontCaption3 = fontCaption3,
    fontCaption3Caps = fontCaption3Caps,
    fontHeadline = fontHeadline,
)
fun vkontakteAndroidDarkTypography(
    fontDisplayTitle1: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.NONE, textStyle = TextStyle(fontWeight = FontWeight(600), fontSize = 23.sp, lineHeight = 28.sp, letterSpacing = TextUnit.Unspecified, )),
    fontDisplayTitle2: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.NONE, textStyle = TextStyle(fontWeight = FontWeight(600), fontSize = 21.sp, lineHeight = 26.sp, letterSpacing = TextUnit.Unspecified, )),
    fontDisplayTitle3: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.NONE, textStyle = TextStyle(fontWeight = FontWeight(600), fontSize = 19.sp, lineHeight = 24.sp, letterSpacing = TextUnit.Unspecified, )),
    fontDisplayTitle4: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.NONE, textStyle = TextStyle(fontWeight = FontWeight(600), fontSize = 17.sp, lineHeight = 22.sp, letterSpacing = TextUnit.Unspecified, )),
    fontTitle1: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.NONE, textStyle = TextStyle(fontWeight = FontWeight(600), fontSize = 24.sp, lineHeight = 28.sp, letterSpacing = TextUnit.Unspecified, )),
    fontTitle2: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.NONE, textStyle = TextStyle(fontWeight = FontWeight(500), fontSize = 20.sp, lineHeight = 24.sp, letterSpacing = TextUnit.Unspecified, )),
    fontTitle3: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.NONE, textStyle = TextStyle(fontWeight = FontWeight(600), fontSize = 17.sp, lineHeight = 22.sp, letterSpacing = TextUnit.Unspecified, )),
    fontHeadline1: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.NONE, textStyle = TextStyle(fontWeight = FontWeight(500), fontSize = 16.sp, lineHeight = 20.sp, letterSpacing = 0.15.sp, )),
    fontHeadline2: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.NONE, textStyle = TextStyle(fontWeight = FontWeight(500), fontSize = 15.sp, lineHeight = 20.sp, letterSpacing = TextUnit.Unspecified, )),
    fontText: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.NONE, textStyle = TextStyle(fontWeight = FontWeight(400), fontSize = 16.sp, lineHeight = 20.sp, letterSpacing = 0.15.sp, )),
    fontParagraph: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.NONE, textStyle = TextStyle(fontWeight = FontWeight(400), fontSize = 15.sp, lineHeight = 20.sp, letterSpacing = TextUnit.Unspecified, )),
    fontSubhead: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.NONE, textStyle = TextStyle(fontWeight = FontWeight(400), fontSize = 14.sp, lineHeight = 18.sp, letterSpacing = 0.15.sp, )),
    fontFootnote: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.NONE, textStyle = TextStyle(fontWeight = FontWeight(400), fontSize = 13.sp, lineHeight = 16.sp, letterSpacing = 0.2.sp, )),
    fontFootnoteCaps: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.UPPERCASE, textStyle = TextStyle(fontWeight = FontWeight(600), fontSize = 13.sp, lineHeight = 16.sp, letterSpacing = 0.2.sp, )),
    fontCaption1: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.NONE, textStyle = TextStyle(fontWeight = FontWeight(400), fontSize = 12.sp, lineHeight = 14.sp, letterSpacing = 0.3.sp, )),
    fontCaption1Caps: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.UPPERCASE, textStyle = TextStyle(fontWeight = FontWeight(600), fontSize = 12.sp, lineHeight = 14.sp, letterSpacing = 0.3.sp, )),
    fontCaption2: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.NONE, textStyle = TextStyle(fontWeight = FontWeight(400), fontSize = 11.sp, lineHeight = 14.sp, letterSpacing = 0.3.sp, )),
    fontCaption2Caps: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.UPPERCASE, textStyle = TextStyle(fontWeight = FontWeight(600), fontSize = 11.sp, lineHeight = 14.sp, letterSpacing = 0.3.sp, )),
    fontCaption3: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.NONE, textStyle = TextStyle(fontWeight = FontWeight(400), fontSize = 9.sp, lineHeight = 12.sp, letterSpacing = 0.3.sp, )),
    fontCaption3Caps: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.UPPERCASE, textStyle = TextStyle(fontWeight = FontWeight(600), fontSize = 9.sp, lineHeight = 12.sp, letterSpacing = 0.3.sp, )),
    fontHeadline: VkTextStyle = VkTextStyle(textTransform = VkTextTransform.NONE, textStyle = TextStyle(fontWeight = FontWeight(500), fontSize = 16.sp, lineHeight = 20.sp, letterSpacing = 0.15.sp, )),
) = VkTypography(
    fontDisplayTitle1 = fontDisplayTitle1,
    fontDisplayTitle2 = fontDisplayTitle2,
    fontDisplayTitle3 = fontDisplayTitle3,
    fontDisplayTitle4 = fontDisplayTitle4,
    fontTitle1 = fontTitle1,
    fontTitle2 = fontTitle2,
    fontTitle3 = fontTitle3,
    fontHeadline1 = fontHeadline1,
    fontHeadline2 = fontHeadline2,
    fontText = fontText,
    fontParagraph = fontParagraph,
    fontSubhead = fontSubhead,
    fontFootnote = fontFootnote,
    fontFootnoteCaps = fontFootnoteCaps,
    fontCaption1 = fontCaption1,
    fontCaption1Caps = fontCaption1Caps,
    fontCaption2 = fontCaption2,
    fontCaption2Caps = fontCaption2Caps,
    fontCaption3 = fontCaption3,
    fontCaption3Caps = fontCaption3Caps,
    fontHeadline = fontHeadline,
)
